### ISSUE TITLE
do you have a preferred way to cite this repo?

### ISSUE THREAD

**Issue by pangyuteng** [Dale-Black/CalciumScoring.jl#15]
Hello staff at MolloiLab. 

Thanks for open sourcing your code.
Let me know if you have a preferred way to cite this repo.
I have ported it to [python](https://github.com/pangyuteng/calcium-scoring/tree/d1af2e0224ad2bd0798a911cbf72cf46d0116bc2).  Soon a PI will be using it, so for now i'm planning on providing them below two references for citing when they are writing grants/publications:

```
Black, Dale, Xingshuo Xiao, and Sabee Molloi. "Coronary artery calcium mass measurement based on integrated intensity and volume fraction techniques." Journal of Medical Imaging 10.4 (2023): 043502-043502.
Gräni, Christoph, et al. "Ultra-low-dose coronary artery calcium scoring using novel scoring thresholds for low tube voltage protocols—a pilot study." European Heart Journal-Cardiovascular Imaging 19.12 (2018): 1362-1371.
```

Thanks.

**Comment by Dale-Black** [comment]
Please cite both of these papers, with whatever format you prefer. Thank you for proper recognition

https://aapm.onlinelibrary.wiley.com/doi/10.1002/mp.16326
https://doi.org/10.1117/1.JMI.10.4.043502

**Comment by Dale-Black** [comment]
Are you interested in collaboration at all? There are still many areas of improvement and robustness testing that could be added to methods like Agatston scoring. I would be able to assist building a proper Python library with the use of [JuliaCall](https://juliapy.github.io/PythonCall.jl/stable/juliacall/) which powers other impressive Python library wrappers like [PySr](https://github.com/MilesCranmer/PySR)

**Comment by pangyuteng** [comment]
Thanks again for sharing your repo!
For research colabs please reach out to the [PIs](https://cvib.ucla.edu/people), it depends on your/their research overlap/interests. :)
